name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Analyze, and Scan Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
          
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
            
      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Trivy scan
        run: trivy fs .

      - name: Build Docker image
        run: docker buildx build -t instruct.ai .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_KEY }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker buildx build --push -t imarchit/instruct_ai:latest .
        
  deploy:
    name: Deploy app to Docker
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Docker pull
        run: docker pull imarchit/instruct_ai:latest

      - name: Image scan
        run: trivy image imarchit/instruct_ai:latest > image-trivy-scan.txt

      - name: Run Docker container
        run: docker run -itd -p 3000:3000 --env-file .env imarchit/instruct_ai:latest
